import { ThemeColor, ThemeMode } from './store';

export interface ThemeTokens {
  bg: string;
  bgCard: string;
  bgInput: string;
  text: string;
  textMuted: string;
  textInverse: string;
  border: string;
  accent: string;
  accentHover: string;
  accentText: string;
  accentRing: string;
  accentLight: string;
  success: string;
  warning: string;
  danger: string;
  xpBar: string;
  navBg: string;
  navActive: string;
  navText: string;
}

const THEMES: Record<ThemeColor, Record<ThemeMode, ThemeTokens>> = {
  blue: {
    dark: {
      bg: 'bg-slate-950',
      bgCard: 'bg-slate-900',
      bgInput: 'bg-slate-800',
      text: 'text-slate-100',
      textMuted: 'text-slate-400',
      textInverse: 'text-slate-900',
      border: 'border-slate-800',
      accent: 'bg-blue-600',
      accentHover: 'hover:bg-blue-500',
      accentText: 'text-blue-400',
      accentRing: 'ring-blue-500',
      accentLight: 'bg-blue-900/40',
      success: 'text-emerald-400',
      warning: 'text-amber-400',
      danger: 'text-red-400',
      xpBar: 'bg-blue-500',
      navBg: 'bg-slate-900',
      navActive: 'text-blue-400',
      navText: 'text-slate-500',
    },
    light: {
      bg: 'bg-slate-50',
      bgCard: 'bg-white',
      bgInput: 'bg-slate-100',
      text: 'text-slate-900',
      textMuted: 'text-slate-500',
      textInverse: 'text-white',
      border: 'border-slate-200',
      accent: 'bg-blue-600',
      accentHover: 'hover:bg-blue-700',
      accentText: 'text-blue-600',
      accentRing: 'ring-blue-500',
      accentLight: 'bg-blue-50',
      success: 'text-emerald-600',
      warning: 'text-amber-600',
      danger: 'text-red-600',
      xpBar: 'bg-blue-500',
      navBg: 'bg-white',
      navActive: 'text-blue-600',
      navText: 'text-slate-400',
    },
  },
  green: {
    dark: {
      bg: 'bg-zinc-950',
      bgCard: 'bg-zinc-900',
      bgInput: 'bg-zinc-800',
      text: 'text-zinc-100',
      textMuted: 'text-zinc-400',
      textInverse: 'text-zinc-900',
      border: 'border-zinc-800',
      accent: 'bg-emerald-600',
      accentHover: 'hover:bg-emerald-500',
      accentText: 'text-emerald-400',
      accentRing: 'ring-emerald-500',
      accentLight: 'bg-emerald-900/40',
      success: 'text-emerald-400',
      warning: 'text-amber-400',
      danger: 'text-red-400',
      xpBar: 'bg-emerald-500',
      navBg: 'bg-zinc-900',
      navActive: 'text-emerald-400',
      navText: 'text-zinc-500',
    },
    light: {
      bg: 'bg-zinc-50',
      bgCard: 'bg-white',
      bgInput: 'bg-zinc-100',
      text: 'text-zinc-900',
      textMuted: 'text-zinc-500',
      textInverse: 'text-white',
      border: 'border-zinc-200',
      accent: 'bg-emerald-600',
      accentHover: 'hover:bg-emerald-700',
      accentText: 'text-emerald-600',
      accentRing: 'ring-emerald-500',
      accentLight: 'bg-emerald-50',
      success: 'text-emerald-600',
      warning: 'text-amber-600',
      danger: 'text-red-600',
      xpBar: 'bg-emerald-500',
      navBg: 'bg-white',
      navActive: 'text-emerald-600',
      navText: 'text-zinc-400',
    },
  },
  orange: {
    dark: {
      bg: 'bg-stone-950',
      bgCard: 'bg-stone-900',
      bgInput: 'bg-stone-800',
      text: 'text-stone-100',
      textMuted: 'text-stone-400',
      textInverse: 'text-stone-900',
      border: 'border-stone-800',
      accent: 'bg-orange-600',
      accentHover: 'hover:bg-orange-500',
      accentText: 'text-orange-400',
      accentRing: 'ring-orange-500',
      accentLight: 'bg-orange-900/40',
      success: 'text-emerald-400',
      warning: 'text-amber-400',
      danger: 'text-red-400',
      xpBar: 'bg-orange-500',
      navBg: 'bg-stone-900',
      navActive: 'text-orange-400',
      navText: 'text-stone-500',
    },
    light: {
      bg: 'bg-stone-50',
      bgCard: 'bg-white',
      bgInput: 'bg-stone-100',
      text: 'text-stone-900',
      textMuted: 'text-stone-500',
      textInverse: 'text-white',
      border: 'border-stone-200',
      accent: 'bg-orange-600',
      accentHover: 'hover:bg-orange-700',
      accentText: 'text-orange-600',
      accentRing: 'ring-orange-500',
      accentLight: 'bg-orange-50',
      success: 'text-emerald-600',
      warning: 'text-amber-600',
      danger: 'text-red-600',
      xpBar: 'bg-orange-500',
      navBg: 'bg-white',
      navActive: 'text-orange-600',
      navText: 'text-stone-400',
    },
  },
  red: {
    dark: {
      bg: 'bg-neutral-950',
      bgCard: 'bg-neutral-900',
      bgInput: 'bg-neutral-800',
      text: 'text-neutral-100',
      textMuted: 'text-neutral-400',
      textInverse: 'text-neutral-900',
      border: 'border-neutral-800',
      accent: 'bg-rose-700',
      accentHover: 'hover:bg-rose-600',
      accentText: 'text-rose-400',
      accentRing: 'ring-rose-500',
      accentLight: 'bg-rose-900/40',
      success: 'text-emerald-400',
      warning: 'text-amber-400',
      danger: 'text-red-400',
      xpBar: 'bg-rose-500',
      navBg: 'bg-neutral-900',
      navActive: 'text-rose-400',
      navText: 'text-neutral-500',
    },
    light: {
      bg: 'bg-neutral-50',
      bgCard: 'bg-white',
      bgInput: 'bg-neutral-100',
      text: 'text-neutral-900',
      textMuted: 'text-neutral-500',
      textInverse: 'text-white',
      border: 'border-neutral-200',
      accent: 'bg-rose-700',
      accentHover: 'hover:bg-rose-800',
      accentText: 'text-rose-600',
      accentRing: 'ring-rose-500',
      accentLight: 'bg-rose-50',
      success: 'text-emerald-600',
      warning: 'text-amber-600',
      danger: 'text-red-600',
      xpBar: 'bg-rose-500',
      navBg: 'bg-white',
      navActive: 'text-rose-600',
      navText: 'text-neutral-400',
    },
  },
  purple: {
    dark: {
      bg: 'bg-zinc-950',
      bgCard: 'bg-zinc-900',
      bgInput: 'bg-zinc-800',
      text: 'text-zinc-100',
      textMuted: 'text-zinc-400',
      textInverse: 'text-zinc-900',
      border: 'border-zinc-800',
      accent: 'bg-violet-600',
      accentHover: 'hover:bg-violet-500',
      accentText: 'text-violet-400',
      accentRing: 'ring-violet-500',
      accentLight: 'bg-violet-900/40',
      success: 'text-emerald-400',
      warning: 'text-amber-400',
      danger: 'text-red-400',
      xpBar: 'bg-violet-500',
      navBg: 'bg-zinc-900',
      navActive: 'text-violet-400',
      navText: 'text-zinc-500',
    },
    light: {
      bg: 'bg-zinc-50',
      bgCard: 'bg-white',
      bgInput: 'bg-zinc-100',
      text: 'text-zinc-900',
      textMuted: 'text-zinc-500',
      textInverse: 'text-white',
      border: 'border-zinc-200',
      accent: 'bg-violet-600',
      accentHover: 'hover:bg-violet-700',
      accentText: 'text-violet-600',
      accentRing: 'ring-violet-500',
      accentLight: 'bg-violet-50',
      success: 'text-emerald-600',
      warning: 'text-amber-600',
      danger: 'text-red-600',
      xpBar: 'bg-violet-500',
      navBg: 'bg-white',
      navActive: 'text-violet-600',
      navText: 'text-zinc-400',
    },
  },
  neutral: {
    dark: {
      bg: 'bg-gray-950',
      bgCard: 'bg-gray-900',
      bgInput: 'bg-gray-800',
      text: 'text-gray-100',
      textMuted: 'text-gray-400',
      textInverse: 'text-gray-900',
      border: 'border-gray-800',
      accent: 'bg-gray-600',
      accentHover: 'hover:bg-gray-500',
      accentText: 'text-gray-300',
      accentRing: 'ring-gray-500',
      accentLight: 'bg-gray-800',
      success: 'text-emerald-400',
      warning: 'text-amber-400',
      danger: 'text-red-400',
      xpBar: 'bg-gray-400',
      navBg: 'bg-gray-900',
      navActive: 'text-gray-200',
      navText: 'text-gray-600',
    },
    light: {
      bg: 'bg-gray-100',
      bgCard: 'bg-white',
      bgInput: 'bg-gray-200',
      text: 'text-gray-900',
      textMuted: 'text-gray-500',
      textInverse: 'text-white',
      border: 'border-gray-200',
      accent: 'bg-gray-700',
      accentHover: 'hover:bg-gray-800',
      accentText: 'text-gray-700',
      accentRing: 'ring-gray-500',
      accentLight: 'bg-gray-100',
      success: 'text-emerald-600',
      warning: 'text-amber-600',
      danger: 'text-red-600',
      xpBar: 'bg-gray-600',
      navBg: 'bg-white',
      navActive: 'text-gray-900',
      navText: 'text-gray-400',
    },
  },
};

export function getTheme(color: ThemeColor, mode: ThemeMode): ThemeTokens {
  return THEMES[color][mode];
}

export const THEME_NAMES: Record<ThemeColor, string> = {
  blue: 'Ocean Blue',
  green: 'Forest Green',
  orange: 'Ember Orange',
  red: 'Crimson Red',
  purple: 'Soft Purple',
  neutral: 'Neutral Gray',
};

export const THEME_SWATCHES: Record<ThemeColor, { light: string; dark: string }> = {
  blue:    { light: '#dbeafe', dark: '#1e3a5f' },
  green:   { light: '#d1fae5', dark: '#064e3b' },
  orange:  { light: '#ffedd5', dark: '#431407' },
  red:     { light: '#ffe4e6', dark: '#4c0519' },
  purple:  { light: '#ede9fe', dark: '#2e1065' },
  neutral: { light: '#f3f4f6', dark: '#111827' },
};
